apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: pingdom-certificate
  namespace: {{ namespace }}
spec:
  secretName: pingdom-tls
  issuerRef:
    kind: ClusterIssuer
    name: lets-encrypt
  dnsNames:
    - {{ hostname }}