apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingdom-deployment
  namespace: {{ namespace }}
spec:
  selector:
    matchLabels:
      app: pingdom
      branch: {{ git_branch }}
  replicas: 1
  template:
    metadata:
      labels:
        app: pingdom
        branch: {{ git_branch }}
    spec:
      containers:
        - name: pingdom-container
          image: ruchira088/pingdom:{{ git_branch }}-{{ git_commit }}
          envFrom:
            - configMapRef:
                name: pingdom-config-map
            - secretRef:
                name: pingdom-secrets
          readinessProbe:
            httpGet:
              port: http4s-port
              path: /health
              httpHeaders:
                - name: X-Correlation-ID
                  value: k8s-readiness-probe
          livenessProbe:
            httpGet:
              port: http4s-port
              path: /health
              httpHeaders:
                - name: X-Correlation-ID
                  value: k8s-liveness-probe
          startupProbe:
            periodSeconds: 5
            failureThreshold: 5
            httpGet:
              port: http4s-port
              path: /health
              httpHeaders:
                - name: X-Correlation-ID
                  value: k8s-startup-probe
          ports:
            - name: http4s-port
              containerPort: 8000
