version: "3"

services:

  pingdom:
    image: pingdom:latest
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
    environment:
      DB_URL: "jdbc:postgresql://postgres:5432/pingdom"
      DB_USERNAME: "admin"
      DB_PASSWORD: "password"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "redis-password"

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "pingdom"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"

  redis:
    image: bitnami/redis
    ports:
      - 6378:6379
    environment:
      REDIS_PASSWORD: "redis-password"
